### ISSUE TITLE
Extra chars (rubbish) in names

### ISSUE THREAD

**Issue by scriptingstudio** [lifenjoiner/nbtscan#1]
After I have switched to v1.5.2 my data fills with extra chars in names.

```
nbtscan152 -h -v -s ; -t 200 -q 192.168.20.0/23
#...
192.168.20.233;WORKGROUP      ;Browser Service Elections
192.168.20.233;WORKGROUP      ;Master Browser
192.168.20.233;☺☻__MSBROWSE__☻;Master Browser
192.168.20.233;MAC;54-be-f7-55-5b-42
192.168.20.237;UV-SKUD        ;Workstation Service
192.168.20.237;FOND-MOS       ;Domain Name
#...

nbtscan151 -h -v -s ; -t 200 -q 192.168.20.0/23
#...
192.168.21.9;WORKGROUP      ;Domain Name
192.168.21.9;MAC;00-00-00-00-00-00
192.168.21.17;__MSBROWSE__;Master Browser
#...
```
![p1](https://user-images.githubusercontent.com/17237559/92684097-50a88f00-f33d-11ea-855c-f2216ff322dd.png)
![p2](https://user-images.githubusercontent.com/17237559/92684101-556d4300-f33d-11ea-822e-56b0ace1709a.png)

Second. Trailing invisible but not whitespace char is added to short hostnames. Maybe it is one-off, I dont know. I cannot trim it. In my case short names are FS2, DC22. I did not test different lengths.
Also trailing invisible char is added to "fond-mos" name. This is "domain name".
I figured out a culprit. The trailing char is "☺".

v1.5.1 produces clean output. I had to switch back to the version with cygwin.

**Comment by lifenjoiner** [comment]
There was a bug on the host name ending position for `-h` or `-d` option. It has been fixed.

But `☺☻__MSBROWSE__☻` is not a bug. You can refer to https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc961857(v=technet.10) for details.

**Comment by scriptingstudio** [comment]
The fix seems to be working. Thanks.
As to `MSBROWSE`. V151 does not output smiles. Does it deliberately cut them?

**Comment by lifenjoiner** [comment]
`x01x02__MSBROWSE__x02\x01` is just the correct (special) name.
`nbtstat` also prints the first 15 characters  as they are: https://superuser.com/questions/1046479/running-nbtstat-a-for-a-router-returns-a-strange-name
Maybe we should keep it as it is.
Refer to the debian version: https://manpages.debian.org/testing/nbtscan/nbtscan.1.en.html
